version: "3.3"
services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "dockerize-it-sample"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "dockerize-it-sample"
      # You can use whatever password you like
      MYSQL_PASSWORD: "dockerize-it-sample"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "dockerize-it-sample"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3310:3306"
    expose:
      - "3306"
    networks:
      - dockerize-it-sample-network
    volumes:
      - dockerize-it-sample-db:/var/lib/mysql
      
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockerize-it-sample
    container_name: dockerize-it-sample
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - "8080:8080"
    networks:
      - dockerize-it-sample-network
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - /home/node/app/.git
    depends_on:
      - db
    command: npm run start
  
networks:
  dockerize-it-sample-network:
    driver: bridge

volumes:
  dockerize-it-sample-db:
  node_modules:
